version: "3.9"

services:
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.securenet-secure.entrypoints=websecure"
      - "traefik.http.routers.securenet-secure.rule=Host(`securenet.photoai.pro`)"
    # volumes:
    #   - .:/app
    depends_on:
      # - db
      - redis
  # db:
  #   image: postgres:13.3
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
    environment:
      - REDIS_HOST=redis
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  redis:
    image: redis
    volumes:
      - ./redis_data:/var/lib/redis/data
    ports:
      - "6379:6379"

networks:
  web:
    external: true
