version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.securenet-secure.entrypoints=websecure"
      - "traefik.http.routers.securenet-secure.rule=Host(`securenet.photoai.pro`)"
    # volumes:
    #   - .:/app
    # depends_on:
    #   - db
  # db:
  #   image: postgres:13.3
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres

networks:
  web:
    external: true
